/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistSessionsRouteImport } from './routes/therapist.sessions'
import { Route as TherapistPatientsRouteImport } from './routes/therapist.patients'
import { Route as TherapistNotesRouteImport } from './routes/therapist.notes'
import { Route as TherapistHomeRouteImport } from './routes/therapist.home'
import { Route as ParentSessionsRouteImport } from './routes/parent.sessions'
import { Route as ParentNotesRouteImport } from './routes/parent.notes'
import { Route as ParentHomeRouteImport } from './routes/parent.home'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as DoctorSessionsRouteImport } from './routes/doctor.sessions'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorNotesRouteImport } from './routes/doctor.notes'
import { Route as DoctorHomeRouteImport } from './routes/doctor.home'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy.$'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistSessionsRoute = TherapistSessionsRouteImport.update({
  id: '/therapist/sessions',
  path: '/therapist/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistPatientsRoute = TherapistPatientsRouteImport.update({
  id: '/therapist/patients',
  path: '/therapist/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistNotesRoute = TherapistNotesRouteImport.update({
  id: '/therapist/notes',
  path: '/therapist/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistHomeRoute = TherapistHomeRouteImport.update({
  id: '/therapist/home',
  path: '/therapist/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentSessionsRoute = ParentSessionsRouteImport.update({
  id: '/parent/sessions',
  path: '/parent/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentNotesRoute = ParentNotesRouteImport.update({
  id: '/parent/notes',
  path: '/parent/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentHomeRoute = ParentHomeRouteImport.update({
  id: '/parent/home',
  path: '/parent/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/parent/children',
  path: '/parent/children',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSessionsRoute = DoctorSessionsRouteImport.update({
  id: '/doctor/sessions',
  path: '/doctor/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorNotesRoute = DoctorNotesRouteImport.update({
  id: '/doctor/notes',
  path: '/doctor/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorHomeRoute = DoctorHomeRouteImport.update({
  id: '/doctor/home',
  path: '/doctor/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/doctor/home': typeof DoctorHomeRoute
  '/doctor/notes': typeof DoctorNotesRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/sessions': typeof DoctorSessionsRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/home': typeof ParentHomeRoute
  '/parent/notes': typeof ParentNotesRoute
  '/parent/sessions': typeof ParentSessionsRoute
  '/therapist/home': typeof TherapistHomeRoute
  '/therapist/notes': typeof TherapistNotesRoute
  '/therapist/patients': typeof TherapistPatientsRoute
  '/therapist/sessions': typeof TherapistSessionsRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/doctor/home': typeof DoctorHomeRoute
  '/doctor/notes': typeof DoctorNotesRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/sessions': typeof DoctorSessionsRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/home': typeof ParentHomeRoute
  '/parent/notes': typeof ParentNotesRoute
  '/parent/sessions': typeof ParentSessionsRoute
  '/therapist/home': typeof TherapistHomeRoute
  '/therapist/notes': typeof TherapistNotesRoute
  '/therapist/patients': typeof TherapistPatientsRoute
  '/therapist/sessions': typeof TherapistSessionsRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/doctor/home': typeof DoctorHomeRoute
  '/doctor/notes': typeof DoctorNotesRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/sessions': typeof DoctorSessionsRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/home': typeof ParentHomeRoute
  '/parent/notes': typeof ParentNotesRoute
  '/parent/sessions': typeof ParentSessionsRoute
  '/therapist/home': typeof TherapistHomeRoute
  '/therapist/notes': typeof TherapistNotesRoute
  '/therapist/patients': typeof TherapistPatientsRoute
  '/therapist/sessions': typeof TherapistSessionsRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/doctor/home'
    | '/doctor/notes'
    | '/doctor/patients'
    | '/doctor/sessions'
    | '/parent/children'
    | '/parent/home'
    | '/parent/notes'
    | '/parent/sessions'
    | '/therapist/home'
    | '/therapist/notes'
    | '/therapist/patients'
    | '/therapist/sessions'
    | '/api/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/doctor/home'
    | '/doctor/notes'
    | '/doctor/patients'
    | '/doctor/sessions'
    | '/parent/children'
    | '/parent/home'
    | '/parent/notes'
    | '/parent/sessions'
    | '/therapist/home'
    | '/therapist/notes'
    | '/therapist/patients'
    | '/therapist/sessions'
    | '/api/proxy/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/doctor/home'
    | '/doctor/notes'
    | '/doctor/patients'
    | '/doctor/sessions'
    | '/parent/children'
    | '/parent/home'
    | '/parent/notes'
    | '/parent/sessions'
    | '/therapist/home'
    | '/therapist/notes'
    | '/therapist/patients'
    | '/therapist/sessions'
    | '/api/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DoctorHomeRoute: typeof DoctorHomeRoute
  DoctorNotesRoute: typeof DoctorNotesRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorSessionsRoute: typeof DoctorSessionsRoute
  ParentChildrenRoute: typeof ParentChildrenRoute
  ParentHomeRoute: typeof ParentHomeRoute
  ParentNotesRoute: typeof ParentNotesRoute
  ParentSessionsRoute: typeof ParentSessionsRoute
  TherapistHomeRoute: typeof TherapistHomeRoute
  TherapistNotesRoute: typeof TherapistNotesRoute
  TherapistPatientsRoute: typeof TherapistPatientsRoute
  TherapistSessionsRoute: typeof TherapistSessionsRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/sessions': {
      id: '/therapist/sessions'
      path: '/therapist/sessions'
      fullPath: '/therapist/sessions'
      preLoaderRoute: typeof TherapistSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/patients': {
      id: '/therapist/patients'
      path: '/therapist/patients'
      fullPath: '/therapist/patients'
      preLoaderRoute: typeof TherapistPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/notes': {
      id: '/therapist/notes'
      path: '/therapist/notes'
      fullPath: '/therapist/notes'
      preLoaderRoute: typeof TherapistNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/home': {
      id: '/therapist/home'
      path: '/therapist/home'
      fullPath: '/therapist/home'
      preLoaderRoute: typeof TherapistHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/sessions': {
      id: '/parent/sessions'
      path: '/parent/sessions'
      fullPath: '/parent/sessions'
      preLoaderRoute: typeof ParentSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/notes': {
      id: '/parent/notes'
      path: '/parent/notes'
      fullPath: '/parent/notes'
      preLoaderRoute: typeof ParentNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/home': {
      id: '/parent/home'
      path: '/parent/home'
      fullPath: '/parent/home'
      preLoaderRoute: typeof ParentHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/parent/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/sessions': {
      id: '/doctor/sessions'
      path: '/doctor/sessions'
      fullPath: '/doctor/sessions'
      preLoaderRoute: typeof DoctorSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/notes': {
      id: '/doctor/notes'
      path: '/doctor/notes'
      fullPath: '/doctor/notes'
      preLoaderRoute: typeof DoctorNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/home': {
      id: '/doctor/home'
      path: '/doctor/home'
      fullPath: '/doctor/home'
      preLoaderRoute: typeof DoctorHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DoctorHomeRoute: DoctorHomeRoute,
  DoctorNotesRoute: DoctorNotesRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorSessionsRoute: DoctorSessionsRoute,
  ParentChildrenRoute: ParentChildrenRoute,
  ParentHomeRoute: ParentHomeRoute,
  ParentNotesRoute: ParentNotesRoute,
  ParentSessionsRoute: ParentSessionsRoute,
  TherapistHomeRoute: TherapistHomeRoute,
  TherapistNotesRoute: TherapistNotesRoute,
  TherapistPatientsRoute: TherapistPatientsRoute,
  TherapistSessionsRoute: TherapistSessionsRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
